// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_realm6assembled = "CgkIvZvXm_QbEAIQCQ"; // <GPGSID>
        public const string achievement_realm1assembled = "CgkIvZvXm_QbEAIQBA"; // <GPGSID>
        public const string achievement_realm7assembled = "CgkIvZvXm_QbEAIQCg"; // <GPGSID>
        public const string achievement_realm2assembled = "CgkIvZvXm_QbEAIQBQ"; // <GPGSID>
        public const string achievement_realm3assembled = "CgkIvZvXm_QbEAIQBg"; // <GPGSID>
        public const string achievement_realm4assembled = "CgkIvZvXm_QbEAIQBw"; // <GPGSID>
        public const string achievement_firstrunfinished = "CgkIvZvXm_QbEAIQCw"; // <GPGSID>
        public const string achievement_thirdpuzzleassembled = "CgkIvZvXm_QbEAIQAw"; // <GPGSID>
        public const string achievement_realm5assembled = "CgkIvZvXm_QbEAIQCA"; // <GPGSID>
        public const string achievement_firstpuzzleassembled = "CgkIvZvXm_QbEAIQAQ"; // <GPGSID>
        public const string achievement_secondpuzzleassembled = "CgkIvZvXm_QbEAIQAg"; // <GPGSID>
        public const string leaderboard_rotochipsscore = "CgkIvZvXm_QbEAIQAA"; // <GPGSID>

}

